[package]
distribution = "2201.13.0"
org = "ballerinax"
name = "github.trigger"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/Team Chat", "Cost/Freemium", "Trigger"]
icon = "docs/icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-github.trigger"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
